statr/config/routes.rb
Statr::Application.routes.draw do |map|

  resources :users do
    resources :mentions
    
    member do
      post :follow, :unfollow
    end
  end
  resources :messages

  resource :session

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  
  root :to => "messages#index"
end

statr/app/models/user.rb
class User < ActiveRecord::Base
  has_many :mentions, :class_name => "Mention", :foreign_key => "mentioning_id"
  has_many :messages
  has_and_belongs_to_many :followees,
    :join_table  => "followees",
    :class_name  => "User",
    :foreign_key => "followee_id" do
    def messages
      Message.where(:user_id => proxy_owner.followees.map(&:id))
    end
  end
  
  validates_presence_of :first_name, :last_name, :username
  validates_presence_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :username
  
  attr_accessor :password
  
  def real_name
    [first_name, last_name].join(" ")
  end
  
  def to_param
    username
  end
  
  def all_messages
    Message.
      where("messages.user_id IN (:user_ids) OR mentioning_id IN (:my_user_id)", {
        :user_ids => followees.collect(&:id) << self.id,
        :my_user_id => self.id
      }).
      select("DISTINCT(messages.content) AS content, messages.*").
      joins('LEFT JOIN "users" ON "users"."id" = "messages"."user_id" LEFT JOIN "mentions" ON "mentions"."mentioning_id" = "users"."id" LEFT JOIN "messages" AS "messages_mentions" ON "messages_mentions"."id" = "mentions"."message_id"').
      order("messages.created_at DESC")
  end
  
  def follow(user)
    followees << find_user(user)
  end
  
  def unfollow(user)
    followees.delete(find_user(user))
  end
  
  def follows?(user)
    !!followees.find_by_username(user.username)
  end
  
  private
  
    def find_user(user_or_username)
      user_or_username.is_a?(User) ? user_or_username : User.find_by_username(user_or_username)
    end
end

statr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :require_login, :only => [:follow, :unfollow]
  
  def show
    if @user = User.find_by_username(params[:id])
      @messages = if logged_in? and current_user == @user
        @user.all_messages
      else
        @user.messages
      end
    else
      flash[:error] = "We couldn't find the user with the username '#{params[:id]}'."
      render "shared/404", :status => 404
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to user_url(@user)
    else
      render :new
    end
  end
  
  def follow
    current_user.follow(params[:id])
    redirect_to user_url(current_user)
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_to user_url(current_user)
  end
  
end

statr/app/helpers/users_helper.rb
module UsersHelper
  
  def follow_user_button
    if logged_in?
      if current_user == @user
        ""
      elsif current_user.follows?(@user)
        content_tag(:span, button_to("Unfollow", unfollow_user_url(@user), :class => "unfollow_button"))
      elsif !current_user.follows?(@user)
        content_tag(:span, button_to("Follow", follow_user_url(@user), :class => "follow_button"))
      end
    end
  end
  
end

statr/app/views/users/_profile.html.erb
<div id="<%= logged_in? ? 'logged_in_user_info' : 'user_info' %>">
  <div id="profile_picture">
    <%= display_user_image_for(@user, :big) %>
  </div>
  <div id="profile_info">
    <div id="username">@<%= @user.username %><%= follow_user_button %></div>
    <div><span id="info_text">real name:</span> <%= @user.real_name %></div>
    <div><span id="info_text">total status updates till now:</span> <%= @user.messages.count %></div>
    <% unless @user.mentions.blank? %>
    <div><span id="info_text">mentioned:</span> <%= link_to @user.mentions.count, user_mentions_url(:user_id => @user.username) %> <span id="info_text">times</span></div>
    <% end %>
    <% unless @user.followees.blank? %>
    <div><span id="info_text">following:</span> <%= pluralize(@user.followees.count, 'person') %></div>
    <% end %>
    <div id="last_status">
      <div><span id="info_text">last status:</span><p>"<%= @user.messages.last.try(:content) %>"</p></div>
    </div>
  </div>
</div>

statr/app/views/users/new.html.erb
<div id="signup_box">
  <%= error_messages_for :user, :header_message => "Some errors occured during the registration process:", :message => nil %>
  <h1>Signup for Statr:</h1>
  <% form_for :user, :url => users_url do |f| %>
    <div class="field_with_label">
      <%= label :user, :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field_with_label">
      <%= label :user, :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="field_with_label">
      <%= label :user, :username %>
      <%= f.text_field :username %>
    </div>
    <div class="field_with_label">
      <%= label :user, :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field_with_label">
      <%= label :user, :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit "Signup" %>
  <% end %>
</div>

statr/app/views/users/show.html.erb
<div id="profile_page">
  <%= render :partial => "users/profile" %>
  <%= render :partial => 'messages/timeline' %>
</div>