statr/config/routes.rb
Statr::Application.routes.draw do |map|

  resources :users do
    resources :mentions
    
    member do
      post :follow, :unfollow
    end
  end
  resources :messages

  resource :session

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  
  root :to => "messages#index"
end

statr/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :content
  validates_length_of :content, :within => 1..140
  
  validates_presence_of :user
  
  after_create :associate_message_to_users_that_have_been_mentioned
  
  scope :latest, :order => "created_at DESC"
  
  private
  
    def associate_message_to_users_that_have_been_mentioned
      mentioned_users = content.scan(/@([\w\d]+)/).flatten
      
      mentioned_users.each do |mentioned_user|
        Mention.create(
          :message        => self,
          :mentioned_user => User.find_by_username(mentioned_user)
        )
      end
    end
end

statr/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :require_login, :only => [:create]
  
  before_filter :load_latest_messages
  
  def create
    @message = current_user.messages.build(params[:message])
    if @message.save
      redirect_to user_url(current_user)
    else
      render :action => "index"
    end
  end
  
  private
    
    def load_latest_messages
      @messages = Message.latest
    end
    
end

statr/app/helpers/messages_helper.rb
module MessagesHelper

  def custom_error_messages_for(message, options = {})
    if message && !message.errors.count.zero?
      html = {}
      [:id, :class].each do |key|
        value = options[key] if options.include?(key)
        html[key] = value.blank? ? 'errorExplanation' : value
      end

      header_message = "We couldn't save this Status because:"

      error_messages = message.errors.map do |attribute_with_error, error|
        content_tag(:li, ERB::Util.html_escape("It #{error}"))
      end.join

      contents = ''
      contents << content_tag(:h2, header_message)
      contents << content_tag(:ul, error_messages)

      content_tag(:div, contents, html)
    end
  end
  
  def display_mention_info_for(message)
    raw '<span class="mentioned_by">mentioned</span>' if message.is_a? Mention
  end
  
  def auto_markup(message)
    link_tags(link_usernames(auto_link(sanitize(message))))
  end
  
  def link_usernames(content)
    content.gsub(/@([\w\d]+)/) do |matched_string|
      content_tag(:span, link_to(matched_string, user_url(:id => $1)), :class => "mentioned_user")
    end
  end
  
  def link_tags(content)
    content.gsub(/#([\w\d]+)/) do |matched_string|
      content_tag(:span, link_to(matched_string, "#"), :class => "tag")
    end
  end

  def display_user_image_for(user, size=:default)
    size_modifier = case size
    when :big
      "_big"
    else
      ""
    end
    
    image_url = File.exists?(File.join(Rails.root, "public/images/user_images/#{user.username}#{size_modifier}.png")) ? "/images/user_images/#{user.username}#{size_modifier}.png" : "/images/default_user_image#{size_modifier}.png"
    
    link_to image_tag(image_url, :alt => "Profile page of #{user.username}", :class => "gravatar_image"), user_url(user)
  end
  
end

statr/app/views/messages/_message.html.erb
<%- div_for message do -%>
  <div class="gravatar">
    <%= display_user_image_for(message.user) %>
  </div>
  <div class="name_of_poster"><%= link_to "@#{message.user.username}", user_url(message.user) %>&nbsp;<%= display_mention_info_for(message) %></div>
  <span><%= auto_markup message.content %></span>
  <span class="date_of_post">–&nbsp;<%= time_ago_in_words message.created_at %> ago</span>
<%- end -%>
<%= content_tag(:div, '&nbsp;', :class => "divider", :id => (@messages.last == message ? 'last' : nil)) %>

statr/app/views/messages/_new.html.erb
<div id="new_status_post">
  <%= custom_error_messages_for @message %>
  <div id="characters_left">140</div>
  <% form_for :message, :url => messages_url do |f| %>
    <%= f.text_area :content, :rows => 3, :class => "textbox", :id => "post_status_update" %>
    <%= f.submit "Post Status", :id => "post_status" %>
  <% end %>
</div>

statr/app/views/messages/_timeline.html.erb
<div id="timeline">
  <% if logged_in? %>
    <%= render "messages/new" %>
  <% end %>
  <div id="messages_list">
    <ul id="tabs">
      <li id="active"><a href="#">recent posts</a></li>
    </ul>
    <div id="messages">
      <% unless @messages.empty? %>
      <%= render :partial => "messages/message", :collection => @messages %>
      <% else %>
        <% if logged_in? %>
          Go ahead and post your first status.
        <% else %>
          Hey, there are no posts yet. Be the first one to post a message. Just <%= link_to "login", login_url %>.
        <% end %>
      <% end %>
    </div>
  </div>
</div>

statr/app/views/messages/index.html.erb
<%= render :partial => 'timeline' %>